#!/usr/bin/env bash
# commands to  Install Nginx

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'

echo "Hello world!" | sudo tee /var/www/html/index.html

# testing nginx configuration
sudo nginx -t

sudo service nginx reload
