#!/usr/bin/env bash
# This script is displaying "Best School" 10 times.

Count=1
while [ "$Count" -lt 11 ]
do
	if [ "$Count" = 4 ]
	then
		echo "bad luck"
	elif [ "$Count" = 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((Count++))
done
