#!/usr/bin/env bash
# Show attached IPs or displays all active IPv4 IPs on the machine

# in different way using ifconfig but now IP is a new command and ifconfig can be missing in some
# ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | awk '{print $2}'

ip -4 -o addr show | awk '{print $4}' | cut -d "/" -f 1
